# Generated by Django 4.1 on 2022-08-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='user_id',
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.CharField(default='abc@crework.com', max_length=255),
        ),
        migrations.AddField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(default='suraj', max_length=255),
        ),
        migrations.AddField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(default='singh', max_length=255),
        ),
    ]
