# Generated by Django 4.1 on 2022-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_remove_tutor_user_id_tutor_email_tutor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
