# Generated by Django 4.1 on 2022-08-09 09:04

from django.db import migrations, models
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_authuser_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='authuser',
            managers=[
                ('objects', tutor.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
